#Jared Singh, G01416039
#CS 262, Lab Section 201
#Lab9
CC = gcc
LIBS = -lm
TARGET = lab10_jsingh51_201
CFLAGS = -g -Wall -std=c99 -pedantic-errors
all: $(TARGET).c
	$(CC) $(TARGET).c -o $(TARGET) $(CFLAGS) $(LIBS)
lab10: $(TARGET).c
	$(CC) $(TARGET).c -o $(TARGET) $(CFLAGS) $(LIBS)
clean:
	rm $(TARGET)
