/* DO NOT EDIT THIS FILE
 * - egul_sched.h (Part of the Egul Scheduler)
 * - Copyright: Prof. Kevin Andrea, George Mason University.  All Rights Reserved
 * - Date: Aug 2024
 *
 *   Definitions for the Egul Scheduler System
 */

#ifndef EGUL_SCHED_H
#define EGUL_SCHED_H

#include "strawhat_process.h"
#include "strawhat_settings.h"

// Process Node Definition
typedef struct egul_process_node {
  pid_t pid;            // PID of the Process you're Tracking
  char *cmd;            // Name of the Process being run
  unsigned short state; // 16-bit: Contains the Flags [C,R,U,S,T] AND Exit Code
  int priority;         // The priority of the Process
  int age;              // How long this has been in the Ready Queue since last run
  struct egul_process_node *next; // Pointer to next Process Node in a linked list
} Egul_process_s;

// Queue Header Definition
typedef struct egul_queue_header {
  int count;            // How many Nodes are in this linked list?
  Egul_process_s *head; // Points to FIRST node of linked list.  No Dummy Nodes.
  Egul_process_s *tail; // Points to LAST node of linked list.  No Dummy Nodes. Optional.
} Egul_queue_s;

// Schedule Header Definition
typedef struct egul_schedule {
  Egul_queue_s *ready_queue;      // Linked List of Processes ready to Run on CPU
  Egul_queue_s *suspended_queue;  // Linked List of Suspended Processes
  Egul_queue_s *terminated_queue; // Linked List of Terminated Processes 
} Egul_schedule_s;

typedef struct create_data {
  char original_cmd[MAX_CMD]; // Original user-input command
  int priority_level;       // Priority level of the Process
  int is_critical;          // 1 if the process is run with critical permissions
  pid_t pid;                // OS Generated, Guaranteed Unique
} Egul_create_data_s;

// Prototypes
Egul_schedule_s *egul_initialize();
Egul_process_s *egul_create(Egul_create_data_s *data);
int egul_insert(Egul_schedule_s *schedule, Egul_process_s *process);
int egul_count(Egul_queue_s *queue);
Egul_process_s *egul_select(Egul_schedule_s *schedule);
int egul_suspend(Egul_schedule_s *schedule, pid_t pid);
int egul_resume(Egul_schedule_s *schedule, pid_t pid);
int egul_exited(Egul_schedule_s *schedule, Egul_process_s *process, int exit_code);
int egul_killed(Egul_schedule_s *schedule, pid_t pid, int exit_code);
int egul_get_ec(Egul_process_s *process);
void egul_deallocate(Egul_schedule_s *schedule);

#endif
