/* DO NOT EDIT THIS FILE
 * - strawhat.h (StrawHat VM)
 * - Copyright: Prof. Kevin Andrea, George Mason University.  All Rights Reserved
 * - Date: Aug 2024
 *
 *   Provides Debug Control Setting for the StrawHat VM
 */
#ifndef STRAWHAT_H
#define STRAWHAT_H

#include "strawhat_scheduler.h"

// Shared Globals
extern int g_debug_mode; 
extern Scheduler_fns_s sched;

#endif
