/* DO NOT EDIT THIS FILE
 * - strawhat_support.h (StrawHat VM)
 * - Copyright: Prof. Kevin Andrea, George Mason University.  All Rights Reserved
 * - Date: Aug 2024
 *
 *   Macros for Printing/Debugging within StrawHat VM
 *   Dependencies - Otur Process Scheduler
 */

#ifndef STRAWHAT_SUPPORT_H
#define STRAWHAT_SUPPORT_H

#include "strawhat_scheduler.h"
#include "strawhat.h"
#include "strawhat_printing.h"

// Adds the __FILE__ from current location before calling abort_error
#define ABORT_ERROR(str) abort_error(str, __FILE__)

// Prints an Informational Message with printf-style formatting arguments
#define PRINT_INFO(str, ...) do {               \
  printf("  %s[Info ]%s ", GREEN, YELLOW);     \
  printf(str, ##__VA_ARGS__);                   \
  printf("%s", RST);                          \
} while(0) 

// If Debug is on, Prints a Debug Message with printf-style formatting arguments
#define PRINT_DEBUG(str, ...) do {              \
  printf(g_debug_mode?"  %s[DEBUG ]%s ":"", CYAN, YELLOW);      \
  printf(g_debug_mode?str:"", ##__VA_ARGS__);                   \
  printf(g_debug_mode?"%s":"", RST);                          \
} while(0) 

// Prints a Status Message with printf-style formatting arguments
#define PRINT_STATUS(str, ...) do {             \
  printf("  %s[Status]%s ", YELLOW, YELLOW);    \
  printf(str, ##__VA_ARGS__);                   \
  printf("%s", RST);                            \
} while(0) 

// Prints a Warning Message with printf-style formatting arguments
#define PRINT_WARNING(str, ...) do {            \
  printf("  %s[Warn  ]%s ", MAGENTA, YELLOW);   \
  printf(str, ##__VA_ARGS__);                   \
  printf("%s", RST);                          \
} while(0) 

// Prints an Error Message with printf-style formatting arguments
#define PRINT_ERROR(str, ...) do {            \
  printf("  %s[ERROR]%s ", RED, RED);   \
  printf(str, ##__VA_ARGS__);                   \
  printf("%s", RST);                          \
} while(0) 

// Prints a Message with Context, with printf-style formatting arguments
#define MARK(str, ...) do {                    \
  printf("  %s[MARK]%s ", MAGENTA, RST);       \
  printf("    %s{%s:%d in %s()}%s ", MAGENTA, __FILE__, __LINE__, __func__, RST); \
  printf(str, ##__VA_ARGS__);                  \
} while(0) 

// Shared Function Prototypes
void register_signal(int sig, void (*handler)(int));
void print_prompt();
void abort_error(char *msg, char *src);
void print_strawHat_banner();
void print_scheduler_debug(Scheduler_s *schedule, Scheduler_process_s *on_cpu);
void print_schedule(Scheduler_s *schedule, Scheduler_process_s *on_cpu);
void print_scheduler_queue(Scheduler_queue_s *queue);
void print_process_node(Scheduler_process_s *node);

#endif
