#Jared Singh, G01416039
#CS 262, Lab Section 201
#Lab2
CC = gcc
CFLAGS = -g -Wall -std=c99 -pedantic-errors
LIBS = -lm
all: lab2_jsingh51_201.c
	$(CC) lab2_jsingh51_201.c -o lab2_jsingh51_201 $(CFLAGS) $(LIBS) 
clean:
	rm lab2_jsingh51_201


