/* Do Not Edit this File
 * - Restrictions on Student Code: Do not post your code on any public site (eg. Github).
 * - Date: Sep 2024
 */

#ifndef MICROFP_PRECISION_H
#define MICROFP_PRECISION_H

// Floating Point Precision
#define MICROFP_SPECIAL      1
#define MICROFP_SIGNED       1
#define MICROFP_DENORMALIZED 1
#define MICROFP_ROUND_EVEN   0
#define MICROFP_SIGN_BITS    1
#define MICROFP_EXP_BITS     3
#define MICROFP_FRAC_BITS    5
#define MICROFP_TOTAL_BITS   MICROFP_SIGN_BITS + MICROFP_EXP_BITS + MICROFP_FRAC_BITS

#endif
