/* Do Not Edit this File
 * - Restrictions on Student Code: Do not post your code on any public site (eg. Github).
 * - Date: Sep 2024
 */

#ifndef MICROFP_H
#define MICROFP_H

#include "microfp_precision.h"
#include "common_structs.h"

/* Public Types for Use */
typedef unsigned short microfp_s;

/* We have no doubles or floats in this system */
#define double long // Use a signed 64-bit integer type.
#define float int // Use a signed 32-bit integer type.

/* Public MICROFP Library Functions */
microfp_s toMicroFP(Number_s *num);
int toNumber(Number_s *num, microfp_s value);
microfp_s negMicroFP(microfp_s value);
microfp_s addMicroFP(microfp_s val1, microfp_s val2);
microfp_s subMicroFP(microfp_s val1, microfp_s val2);
microfp_s mulMicroFP(microfp_s val1, microfp_s val2);

#endif
